### PR TITLE
LordOfNightmares custom cards :D ATTEMPT 3(PogChamp)

### PR DESCRIPTION
**Pull request by LordOfNightmares**
Re-balanced removed 3'rd & 4'th effect.
there still might be bugs left but i didn't see them.
still not adapted for mr4 i will try to addapt them tho soon

### CODE REVIEW

**Comment by Gideon9212** [comment]
If you removed the 3rd and 4th effects, why does the cdb still have them?

_Sent from my Samsung SM-G935T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LordOfNightmares** [comment]
hmm what i remember i sent you the right one maybe i made a mistake well anyway i uploaded the ver with mr4 support as well

**Comment by AndreOliveiraMendes** [comment]
observation about Odd-Eyes Exceed Magician pendulum effect's.
> Once per turn: You can target 1 Xyz Monster you control; this turn, its Rank becomes 7, also it is treated as having a Level that is equal to its Rank.

that use other effect, EFFECT_RANK_LEVEL_S (check xiangke magician anime [511002096]), so you would change the line 89-94 to

>local e1=Effect.CreateEffect(e:GetHandler())
        e1:SetType(EFFECT_TYPE_SINGLE)
        e1:SetCode(EFFECT_RANK_LEVEL_S)
        e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
        tc:RegisterEffect(e1)

the segond seems to work fine.

**Comment by Gideon9212** [comment]
CDB Still incorrect. You have it listed as TCG / OCG when it needs to be custom.
I have a feeling you do not know how or have your data editor x not setup for it. 
[cardinfo_english.txt](https://github.com/Gideon9212/Livecustom/files/1258940/cardinfo_english.txt)
Place this file into the data folder. It will list the VG and custom options.

You also have 

> (This card's name can also be treated as "____".)

Listed twice on the monster effects on all of them AND on Odd-Eyes Exceed Magician listed above the pendulum effect for some reason.

Fix the cdb, we will check the scripts, and when both are 100%, this will be merged finally as the effects are now balanced enough.

**Comment by AndreOliveiraMendes** [comment]
i have a question, why do you have that

>    if not c515958930.global_check then
        c515958930.global_check=true
        local e0=Effect.GlobalEffect()
        e0:SetType(EFFECT_TYPE_FIELD)
        e0:SetCode(EFFECT_ADD_CODE)
        e0:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
        e0:SetTarget(function(e,c) return getmetatable(c)==c515958930 end)
        e0:SetTargetRange(0xff,0xff)
        e0:SetValue(16195942)
        Duel.RegisterEffect(e0,0)
    end

why you used?

> getmetatable(c)==c515958930

**Comment by Gideon9212** [comment]
Oh and forgot to say:
For cards with This card's name is also treated as ____
The alias ID must be the card name your using. (Above code aka the card number, you put the card number of the card name your using.)
Any questions on that just let me know.

**Comment by LordOfNightmares** [comment]
Well i didn't want aliases so that is why i put it as `can also be treated as "____".` not ` is also treated as`,also my database doesn't have `(This card's name can also be treated as "____".)` listed twice wtf?!

Ah and as duel.getmasterrule doesn't work i guess i don't know how to make it work on both mr3 and mr4 because LOCATION_PZONE doesn't exist fully implemented in mr3... so they use Location_Szone...
@AndreOliveiraMendes i don't know =D that one piece of code was given to me to make it work under xyz materials as well

**Comment by AndreOliveiraMendes** [comment]
@LordOfNightmares well, if that the intention, you need to say

> this card is also treated as _ while on field or grave

you card have basicaly same clause as **Neo-Spacian Marine Dolphin**, wich is also treated as **Neo-Spacian Aqua Dolphin**, and acording konami ruling abot [max of 3 rule](http://yugioh.wikia.com/wiki/Maximum_of_3_Rule) you still have limitation (can't put 3 of each, even trought they stored in diferent places), also **Marine Dolphin** uses alias and have a effect to "add code" to add own code (check these card if you curious).

**Comment by Gideon9212** [comment]
Still waiting for your next CDB and other stuff. Consider making a new pull if its having issues.

**Comment by LordOfNightmares** [comment]
well i got some issues with mr4 still i think

**Comment by AndreOliveiraMendes** [comment]
where you testing it?

**Comment by Gideon9212** [comment]
Consider asking us if you need help in #script

**Comment by LordOfNightmares** [comment]
@AndreOliveiraMendes well i was testing it in ygopro2 =p so i guess i just gotta wait until a stable version appeares

**Comment by AndreOliveiraMendes** [comment]
btw, why you need get.masterrule? :v

**Comment by LordOfNightmares** [comment]
emm some functions :P have different forms so i don't know

**Comment by LordOfNightmares** [comment]
@Gideon9212 i think it works after the last update

**Comment by LordOfNightmares** [comment]
@Gideon9212 now for sure after "minor text fix in cdb"

**Comment by AndreOliveiraMendes** [comment]
(This card's name can also be treated as "Clear Wing Synchro Dragon".)
i still don't get that, the script make that not opcional ~~does opcional clause even exist?~~

**Comment by LordOfNightmares** [comment]
i don't know about that but i don't want it  to be just "this card is also treated as **"Clear Wing Synchro Dragon""** cuz then that interferes with the card limitation therefor i choose "**can** also be treated as"

**Comment by Gideon9212** [comment]
Gota fix alias on cdb.

**Comment by LordOfNightmares** [comment]
what alias?

**Comment by LordOfNightmares** [comment]
alias interacts with the real card id in cdb so it doesn't work as said i don't want a Neo spacian twinkle moss... therefor **can also be treated as** not **is also treated as** see the **can**

**Comment by AndreOliveiraMendes** [comment]
find a way to make it optional they, because you global effect is not optional at all

**Comment by LordOfNightmares** [comment]
Hmm I finally an effect that would not interfere with all the things you mentioned came to my mind.
(While this card isn't in your deck its name is also treated as "x")
where x is their respective dragon counterpart?

**Comment by LordOfNightmares** [comment]
so @Gideon9212 what do you think about that?↑

**Comment by Gideon9212** [comment]
So your trying to make a alia's that isn't a alias which would allow for weird interactions? Uh....no.
That and if you want to change them again, please consider closing this pull and making a new one.

**Comment by LordOfNightmares** [comment]
:(

**Pull request closed without merging**
