### PR TITLE
Dark Magician Custom #1 by Larry126

### PR DESCRIPTION
**Pull request by larry126**
Dark Magic Endow
Discard 1 Level 6 or higher DARK Spellcaster-Type monster or 1 "Legendary Dragon" Spell Card or 1 card that specifically lists the card "Dark Magician" or "Dark Magician Girl" or "Magician of Black Chaos" in its text; draw 2 cards.

Dark Magic Screen
When this card is activated: You can add 1 "Dark Magician" or 1 "Legendary Dragon" Spell Card or 1 Spell/Trap Card that specifically lists the card "Dark Magician" from your Deck to your hand, except "Dark Magic Screen". You can only use this effect of "Dark Magic Screen" once per turn. If you control "Dark Magician": Continuous Spell/Trap Cards you control cannot be targeted or destroyed by your opponent's card effects. You can only control 1 "Dark Magic Screen".

Dark Magic Contract
You can shuffle 1 face-down Spell/Trap Card or 1 other face-up Continuous Spell/Trap Card you control into the Deck; activate 1 Continuous Spell/Trap Card that specifically lists the card "Dark Magician" from your Deck. During your Main Phase: You can send this card you control to the Graveyard; Target up to 3 "Legendary Dragon" Spell Cards or cards that specifically list the card "Dark Magician" or "Dark Magician Girl" or "Magician of Black Chaos" in your Graveyard, except "Dark Magic Contract"; shuffle them into the Deck, then draw 1 card. You can only use each effect of "Contract with the Dark Magic" once per turn.

### CODE REVIEW

**Comment by AlphaKretin** [comment]
The following is my opinion, Gideon gets the final say.

Dark Magic Endow: Yowza that text is a mess for a simple Trade-In equivalent. Maybe you could make it work on "Level 6 or higher DARK Spellcaster-type" monsters, compress the list of individual monsters a bit? So that would be "Discard 1 Level 6 or higher DARK Spellcaster-type monster, "Legendary Dragon" Spell Card, or card that specifically lists "Dark Magician", "Dark Magician Girl", or "Magician of Black Chaos;". Still a bit of a mouthful, but more reasonable.

**Comment by Gideon9212** [comment]
I have to go with what alpha said. Dark Magic Endow needs a text change.
When that's done, I'll merge.

**Comment by larry126** [comment]
Okay, I have updated all the cards:
Firstly, followed what Alpha suggested, Dark Magic Endow now send 1 DARK Spellcaster-Type monster instead of listing all the specific card names.
Secondly, I changed the effect of Dark Magic Contract from "You can shuffle 1 other Spell/Trap Card" to "You can shuffle 1 face-down Spell/Trap Card or 1 other face-up Continuous Spell/Trap Card", therefore I cannot activate its effect by shuffling 1 activated Quickplay Spell or Normal Trap Cards which the benefit is beyond my expectation (as in which this can be a way to recycle Spell/Trap back and allows combo like Contract+Illusion Magic+1 Spellcaster to bring out Dark Magician very quickly with the cost of only tributing 1 Spellcaster) wasn't my intention when creating this card. The idea is that you can shuffle back redundant Spell/Trap or Continuous Spell/Trap that is about to leave the field (like shuffle Eternal Soul back to prevent its backfire) to place 1 new and more useful one on to the field.

**Comment by Gideon9212** [comment]
Looks fine. Merging

**Pull request merged**
