### PR TITLE
Added "Nemesis Fusion"

### PR DESCRIPTION
**Pull request by EerieCode**
**Nemesis Fusion** (210220096)
Counter Trap
When your opponent activates a card or effect that would Fusion Summon a Fusion Monster: Pay 1000 LP, then declare 1 Fusion Monster's card name; your opponent looks at their Extra Deck and reveals 1 monster with the declared name, if any, and if they do, negate that effect, then your opponent Fusion Summons the declared monster, if possible, from their Extra Deck to your side of the field, using monsters they control or in their hand as Fusion Materials (you choose the summoned monster's position). You can only activate 1 "Nemesis Fusion" per turn.

Artwork ready in the pull [at this link](https://github.com/Gideon9212/CustomArtwork/pull/20).

### CODE REVIEW

**Comment by EerieCode** [comment]
Effect modified as per private conversation:

- The cost now also requires you to discard 1 card, in addition to the LP cost.
- The materials for the Fusion Summon must be face-up monsters on the opponent's field.

**Comment by Gideon9212** [comment]
Remove LP cost. Only need's discard cost.
Remove face-up monsters on the field and re-allow in their hand too. This is a very situational counter trap, it doesn't need more limits.

**Comment by EerieCode** [comment]
I'll remake the pull later changing the cost, this way we'll reduce the number of commits. I was considering leaving the materials as field-only, though, that change was less for balance purposes and more to ensure the materials used would only come from publicly known locations.

**Comment by AlphaKretin** [comment]
You could make it reveal the hand first (or maybe "any valid fusion materials for the declared monster"?), and because that grants knowledge it might justify a higher cost instead of it needing to be reduced?

**Comment by Gideon9212** [comment]
Reveal hand before declare progress. It doesn't need a higher cost. Even knowing the materials used, you can still declare wrongly. (Example, your opp activates 3 poly while having 3 blue eyes in hand. You declare neo blue eyes ultimate, end up he has none in the extra and was going to summon blue eyes twin.)
No need to make a cost higher for a counter trap that can in fact, not negate anything if declared wrong, and also be a hard to search counter trap for **very** situational cases. Most general negation would do better. 
Only reason it needs the discard cost tbh is to prevent +4 gains if you use this on five-headed dragon or other large stuff. Other wise you have a chance to activate a counter trap, end up declaring wrong and losing 2 cards.

**Comment by EerieCode** [comment]
So, the revamped effect would be something among these lines:

When your opponent activates a card or effect that would Fusion Summon a Fusion Monster: discard 1 card, also have the opponent reveal the cards in their hand (if any), then declare 1 Fusion Monster's card name; your opponent looks at their Extra Deck and reveals 1 monster with the declared name, if any, and if they do, negate that effect, then your opponent Fusion Summons the declared monster, if possible, from their Extra Deck to your side of the field, using monsters in their hand or face-up monsters they control as Fusion Materials (you choose the summoned monster's position). You can only activate 1 "Nemesis Fusion" per turn.

**Comment by Gideon9212** [comment]
Perfect revamped. Soon I see pull modified for it, will merge.

**Pull request closed without merging**
