### PR TITLE
Crystal Beast Support

### PR DESCRIPTION
**Pull request by Evolkaiser**
Cards are pretty straightforward tbh

### CODE REVIEW

**Comment by AlphaKretin** [comment]
As always this is just my opinion, but it might be worth holding off on this until we get more news about Legend Duelist 2. A trustworthy rumour places Crystal Beast support in the pack, and if it's right, there's a slim chance said support conflicts with the design of these cards.

**Comment by Evolkaiser** [comment]
I literally had no idea Crystal Beast support was rumored, definitely better to not implement them then .

**Comment by Gideon9212** [comment]
I'll keep this PR open and review them when more news of the support comes into light.

**Comment by Gideon9212** [comment]
From what it looks like, none of the new support I seen are close to yours. 
So this passes however the ID's are in the wrong range. Please change IDs to at least start with 515

**Comment by Evolkaiser** [comment]
Thoughts now that 3 of 4 cards have been revealed for Crystal Beasts?

**Comment by AlphaKretin** [comment]
I'm not sure how I feel about having a Rainbow Dragon retrain. On one hand the official support just got one, on the other you can summon that with this. It returning banished beasts works with Overdragon banishing beasts, and the trap that summons Overdragon can set up a grave to banish for this. 🤔 

The other two cards don't conflict at all, because they actually support freaking Crystal Beasts instead of Konami's pathetic desperation to make people play Rainbow Dragon.

**Comment by Evolkaiser** [comment]
oh BTW card numbers have been fixed.

**Pull request merged**
