### PR TITLE
This new card

### PR DESCRIPTION
**Pull request by NagareHisui**

### CODE REVIEW

**Comment by AndreOliveiraMendes** [comment]
it missing custom ot (0x20 in hex, and 32), you should check the cdb.

**Comment by Gideon9212** [comment]
The issues are exactly as andre said.
Fix above issues and I'll merge.

**Comment by NagareHisui** [comment]
I see. So where exactly do I put the 0x20 and 30 numbers? If you can show me via screenshot that would be helpful.

**Comment by AndreOliveiraMendes** [comment]
@NagareHisui 
are you using sqlite or dataeditor?

**Comment by NagareHisui** [comment]
Data editor

**Comment by AndreOliveiraMendes** [comment]
inside the folder you extracted dataeditor, there a folder called data, and there a file caled cardinfo_english.txt, open that file, they edit the first lines to

> ##rule
0x0	Rule
0x1	OCG
0x2	TCG
0x3	OCG&TCG
0x4	Anime/DIY
0x8	VG
0x10	illegal
0x20	Custom

separate the number's and text by tab and not space.

**Pull request closed without merging**
