### PR TITLE
LordOfNightmares custom cards :D ATTEMPT 2

### PR DESCRIPTION
**Pull request by LordOfNightmares**
changed id's to 51595893x.
Re-made some text errors closer to psct.
Fixed the bugs.
Also Odd-eyes Slayer Magician has 1 pendulum effect on comparison to others because his effect outclasses the other Odd-eyes Macicians pendulum effects + its a 2 in 1 effect.

### CODE REVIEW

**Comment by ClementLouis** [comment]
Your PSCT still need a lot of work, random exemple that I think is a error from your psct:
the (1) effect of the magician treated as DRXD, given your wording you can (since it is not a hard OPT):
attach it to a Xyz monster=>detach it to activate that Xyz effect => attach it again => activate the Xyz monster effect again if there is OPT limitation => repeat

Same for the balance of your cards, they are clearly overpowered
just a random exemple:
    place the magician treated as DRXD and the scale 11 
    Psummon the one that get 150 x sum of the scale
    use the effect to change the DRXD magician to scale 13
    11+13=24
    24*150=3600
    you have a monster that gain 3600 atk for free (and can be brought back later since it is a pendulum)
another exemple:
you cannot deal with the pendulum unless you find a way that don't destroy them since once they are destroyed, you immediatly place them again in the Pzone using their effect 
and I found that only by quickly checking the text

I'm just speaking design wise, I did not checked the scripts

**Comment by LordOfNightmares** [comment]
all was inteded tho =-D 3900 atk at 2x13 scales but you can negate it and its 0 atk or destroy either scale cuz there is no point in keeping 2 scales that are big and odd-eyes exceed magician in pen scale is like an easy way to bypass if you got the one that gains atk/def of the scales value its not that strong tho i still believe zefras are stronger...and the DRXD magician to xyz into whatever xyz monster rank level is equal to its level using him as one material then use material then attach once from grave only. you could say basically its 1 monster 2 materials per turn.
As the scripts work i intended it to do those kinds of effects like that.

**Comment by Gideon9212** [comment]
I will check when I get home but a nerf is most likely required. 
Metalfoes + this = madness

_Sent from my Samsung SM-G935T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Gideon9212** [comment]
PSCT still needs fixed. Still a few spacing errors, still a few missing . or -.
OCG and TCG tag is used when the OT should be 32 (the custom tag)
Some nerfs are needed. I'll break it down.
The main effect that should be removed from all the cards is "You can destroy this card in your hand and 1 card on your side of the field."
Fire kings, yubel, metalfoes, etc can gain from this so much. Combine with the scales being as good as gates, even a turbo god deck can be made from this considering the magician archtype search. It also bypasses anti-spell fragrance, and having the destroy as a cost, preventing your opp from reacting at all.
We don't want a stable pend that can be used in almost everything destroy related. It can grant net plus's that I can't even begin with. This should be removed on all 4.
Depending on how you redo the monster effects from bellow, the 4th effect should be fine longs you state that destroyed while as a monster. Other wise with current wording (I haven't looked at the scripts, my main focus is wording) it allows to be destroyed as a pend scale and come back right away.
Breaking it down from each one now.
Odd-Eyes Exceed Magician
First p effect is perfectly fine. Xyzs most of the time don't want a level. 
2nd p effect is a bit strong. Considering the MR4 rules, you want to return monsters if it isn't good for the current board state and you get a plus of a chance to pend summon anything. For now, lets leave this alone.
1st monster effect is a bit strong. Sure it doesn't touch the grave often but when it does, it can reload a xyz.
2nd effect is confusing to me. "You can Xyz summon 1 xyz monster from your extra deck using this card as xyz material." Does this mean I can xyz summon any xyz monster with any rank using that one card? If so, this will create a lot of issues, if not, reword this.
3rd effect needs removed for reason stated earlier.
4th effect is fine longs the 3rd is removed and the 2nd is cleared up.
Odd-eyes Blood magician
"You can destroy 1 card in pendulum zone except itself and if you do add 1 "Odd-Eyes" monster from your deck to hand, this effect can be used once per turn."
This needs reworded to the following to prevent loops.
You can destroy 1 card in pendulum zone except "Odd-eyes Blood magician" and if you do add 1 "Odd-Eyes" monster from your deck to hand, this effect of "Odd-eyes Blood magician" can be used once per turn.
This makes it a hard once per turn, preventing using 2 blood magicians to use their effect on each other over and over.
2nd p effect is a free reusable fusion gate without the banish cost with a non hard once per turn. 
You can do one of the following
-Lock it with the magician and odd-eyes archtype.
-Lock it with a once while this card is on the field. This allows you to use exceed or other self destroy effects to reset it without being op considered the 3rd effect will be removed.
-Have the materials banish.
-Remove effect for another effect.
1st monster effect is fine.
2nd monster effect is a lose 1 turn but with extra deck monsters without any downsides to your self. Consider making it a once while this card on the field effect or lock it to prevent your opp from fusion summoning or something close to that.
3rd effect needs removed for reason stated earlier.
4th effect on this one is fine depending on how you redo the 2nd monster effect. 
Odd-eyes Slayer Magician
First pend effect is fine longs you hard turn lock it and you reword it.
First monster effect is fine considering the stats of the card.
2nd effect needs reworded (it has a error) and hard turn locked if you keep 4th effect.
3rd effect needs removed for reason stated earlier.
4th effect can stay if 2nd effect is hard turn locked. If its not, then this needs removed.
Odd-Eyes Illusory Magician
1st pend effect needs hard turn locked. 
2nd pend effect needs ether a archtype lock or tread the monster as just a turner, not to change their level to 2 and make them a tuner. I don't even want to think about how much metalfoes can abuse this.
First monster effect is fine. Quite interesting tbh.
2nd effect is fine. 
3rd effect needs removed for reason stated earlier.
4th effect is fine. This one was the most bal out of all of them monster effect wise. The pend effect on the 2nd, however is quite abusable to even the most odd type decks (cardians)
Note that all what I said is advice. Its your cards, however, in the current state of balance of them, please consider reading it if you wish it to be added. 
For now, this will not be added.

**Comment by edo9300** [comment]
Another thing related to the scripts, for mr4 support you have to check location pzone 0/1 not location szone

**Comment by edo9300** [comment]
Another thing related to the scripts, for mr4 support you have to check location pzone 0/1 not location szone

**Comment by LordOfNightmares** [comment]
@edo9300 i know about the mr4 support but for some reason i can't make global variables that will help me to transition that make that...
`local loc=LOCATION_SZONE
    local l,r=6,7
	if Duel.GetMasterRule and Duel.GetMasterRule()>=4 then loc,l,r=LOCATION_PZONE,0,1 end
	if Duel.GetMasterRule and Duel.GetMasterRule()>=4 then loc,l,r=LOCATION_PZONE,0,1 end`
@Gideon9212 about nerfing them i don't know man well i could lock some effects to only magician/odd-eyes archtype ,when i made them i just wanted to make a pendulum archtype that will bypass solemns, bunch of other negations (i hate all negations they are super annoying and i hate zefrastellarknights) and anti-spell fragrance that was all i had in mind,pendulum summon zarc,odd-eyes wing ,odd-eyes venom, bypass the supreme king gates summoning nomi and make each of them represent those 4D dragons so they would have each 1 pendulum effect and 1 monster effect for their  for their summon counterpart.

_•3rd and 4th effect on each card was to prevent negations and anti-spell fragrance.if you know a better effect that will help with switching scales and prevent those 2 annoying features of the game tell me._

•Odd-Eyes Illusory Magician
1st pend effect is hard turn locked.("this effect can only be used once per turn") 
meaning even if the scale is reseted it can't be used more than once ,i don't know if that is the psct correct way to say it tho,i just bounded it to the effect usage,in general.
2nd pend eff **i will lock it to odd-eyes and magicians only archtype.**

•Odd-eyes Slayer Magician
1st pend effect is hard turn locked it says clearly "second time" not third or fourth time
but i **might need to reword the ignoring summoning conditions part, cuz i want it to be bound to the 2nd pendulum summon.**
2nd monster effect i can make it hard turn locked by adding ("this effect can only be used once per turn") if i am thinking wrong in psct tell me how i could hard turn lock it properly in words.

**•Odd-eyes Blood magician**
1st pend effect that lets me destroy the other scale and add one odd-eyes i hard locked it script wise and again i don't know the psct way to hard turn lock it.
2nd pend effect (fusion) **i will lock it to only fusion with magician or odd-eyes archtype 
also i could add cost to shuffle a monster from hand or FaceupExtra deck in order to use it**
2nd monster effect (welp this one was first its 2nd pend effect then i thought that this is op :D) its more of a random effect that came in my mind i think **i will change it to a once per turn starving venom copy effect just during your opponent turn only.**

**•Odd-Eyes Exceed Magician**
1st monster effect i could limit it to only dragon type xyz monters?(does that sound better)
2nd effect means you can xyz summon any xyz monster whos rank is equal to this card's level.
meaning its level 5 then you can xyz summon any of all rank5 monsters (ignoring material condition-like a rank-up-magic).**i will nerf it to only dragon types monsters then.**

**Comment by edo9300** [comment]
LOCATION_PZONE is used not only in mr4, but in previous ones too

**Comment by LordOfNightmares** [comment]
i tried using LOCATION_PZONE i mean i first scripted the cards for mr4 =D then i remade them for percy cuz they had bugs when i used the LOCATION_PZONE...

**Comment by Gideon9212** [comment]
PSCT wise to hard turn lock:
"You can only use this effect of (card name here) once per turn."

> •Odd-Eyes Exceed Magician 1st monster effect i could limit it to only dragon/spellcaster type xyz monsters and add a cost of 500LP? 

Don't need the lp cost. The limit to dragon/spellcaster's xyz's should be enough.

If you wish to prevent your cards to be used with god cards, add the following pend effects on all of them.
"You cannot pendulum summon creator god type monsters." 
Though if you do all your current nerfs, you don't have to add this. 

> •Odd-eyes Blood magician 2nd pend effect (fusion) i will lock it to only fusion with magician or odd-eyes archtype
also i could add cost to shuffle a monster from hand or FaceupExtra deck in order to use it

Locking it with the archtype should be fine enough. Don't need the shuffle. Not trying to super nerf.

> •Odd-eyes Slayer Magician but i might need to reword the ignoring summoning conditions part, cuz i want it to be bound to the 2nd pendulum summon. also it can be used even if it leaves the field in that sense :D

Yes, please reword.

> 3rd and 4th effect on each card was to prevent negations and anti-spell fragrance.if you know a better effect that will help with switching scales and prevent those 2 annoying features of the game tell me.

Thing is, that feature is what makes it balanced. To quote myself on the github readme

> If you were the opponent, would you have a major problem trying to play around or get rid of this card?

Doing that makes it only way to remove is s/t removal, which is annoying and causes problems.
That being said, you can add the following:
"This card is unaffected by anti-spell fragrance." 
Idk how to do that script wise but if you do add that, add the creator god thing I said above.

I'll be waiting for your next cdb before I review again.

**Comment by Gideon9212** [comment]
@LordOfNightmares We found out that 10 numbers cause overflow. Please use 9 when you remake cdb.

**Comment by LordOfNightmares** [comment]
3rd time woooo

**Pull request closed without merging**
