### PR TITLE
LordOfNightmares custom cards :D

### PR DESCRIPTION
**Pull request by LordOfNightmares**
LordOfNightmares custom cards Odd-Eyes Exceed Magician, Odd-Eyes Blood Magician, Odd-Eyes Slayer Magician, Odd-Eyes Illusory Magician. =D
AntiMetaman said i could pull a request :D

### CODE REVIEW

**Comment by LordOfNightmares** [comment]
oh it currently has some bugs will fix later

**Comment by Gideon9212** [comment]
@LordOfNightmares IDs too close to our anime IDs. Check for psct and bal needed.
Other collbs do not merge for now.

_Sent from my Samsung SM-G935T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Gideon9212** [comment]
Some of the PSCT needs cleaned up.
Few of the cards are missing a space like Extra Deck or missing a dash like Face-up (Some cards have it as ExtraDeck or Faceup)
Cards don't need their effects numbered but I'm fine with it. Only one that bugs me is Slayer Magician since it only has one pendulum effect.
To quote Slayer Magician
"2)Once per turn you can destroy this card on the and 2 other cards on your side of the field."
"on the and" you can remove on the since its has to be on the field anyway.
To quote slayer Magician again
"4)When destroyed you can place this card in pendulum zone."
Should be "When this card is destroyed; you can place this card in the pendulum zone."

Please consider fixing the PSCT issues, changing the IDs to 515 or higher or some other number, and uploading fixed scripts (you said there where bugs) on your next upload and I'll relook again.

**Comment by LordOfNightmares** [comment]
Odd-eyes Slayer magician has only 1 pendulum effect cuz his effect is outclasses other 3 odd-eyes magician cards pendulum effects plus its a double effect in 1 so even if that card will leave the field the effect will remain till end phase.
-------[ Pendulum Effect ]-------
1)Once per turn activate this effect:
•You can pendulum summon a seccond time; monsters pendulum summoned by this effect from Faceup Extradeck have effect(s) negated until end phase.
•You can pendulum summon from Faceup Extradeck (ignoring summoning conditions).

**Pull request closed without merging**
