### PR TITLE
Gh8stree c210310305.lua

### PR DESCRIPTION
**Pull request by Gh8stree**

### CODE REVIEW

**Comment by Gh8stree** [comment]
Did I do it right?

**Comment by AndreOliveiraMendes** [comment]
it is only 1 script? where the rest of files?

**Comment by Gh8stree** [comment]
Here:
--Fog Dualities
--Scripted by Tree and Radioboy
function c210310305.initial_effect(c)
   --Activate
   local e1=Effect.CreateEffect(c)
   e1:SetType(EFFECT_TYPE_ACTIVATE)
   e1:SetCode(EVENT_LEAVE_FIELD)
   c:RegisterEffect(e1)
   --special summon
   local e2=Effect.CreateEffect(c)
   e2:SetDescription(aux.String210310305(210310305,0))
   e2:SetCategory(CATEGORY_SPECIAL_SUMMON)
   e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
   e2:SetProperty(EFFECT_FLAG_DELAY)
   e2:SetRange(LOCATION_FZONE)
   e2:SetCode(EVENT_LEAVE_FIELD)
   e2:SetCountLimit(1,210310305)
   e2:SetCondition(c210310305.spcon1)
   e2:SetTarget(c210310305.sptg1)
   e2:SetOperation(c210310305.spop1)
   c:RegisterEffect(e2)
   --other special summon
   local e3=e2:Clone()
   e3:SetCountLimit(1,210310305+100)
   e3:SetCondition(c210310305.spcon2)
   e3:SetTarget(c210310305.sptg2)
   e3:SetOperation(c210310305.spop2)
   c:RegisterEffect(e3)
   --add counters
   local e4=Effect.CreateEffect(c)
   e4:SetType(EFFECT_TYPE_IGNITION)
   e4:SetCode(EVENT_FREE_CHAIN)
   e4:SetProperty(EFFECT_FLAG_CARD_TARGET)
   e4:SetCountLimit(1,210310305+200)
   e4:SetTarget(c210310305.target)
   e4::SetOperation(c210310305.activate)
   c:RegisterEffect(e4)
end
(edited)
--first type of special summon e2
function c210310305.cfilter1(c,tp)
   return c:GetPreviousControler()==tp and c:IsPreviousLocation(LOCATION_MZONE) and bit.band(c:GetPreviousRaceOnField(),RACE_FAIRY)==0 and c:IsArchetype(Archetype_0x18) and c:IsPreviousPosition(POS_FACEUP)
end
function c210310305.spcon1(e,tp,eg,ep,ev,re,r,rp)
    return eg:IsExists(c210310305.cfilter1,1,nil,tp)
end
function c210310305.spfilter1(c,e,tp)
   return  c:IsArchetype(Archetype_0x18) and c:IsRace(RACE_AQUA) and c:IsCanBeSpecialSummoned(e,0,tp,false,false)
end
function c210310305.sptg1(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
        and not e:GetHandler():IsStatus(STATUS_CHAINING)
        and Duel.IsExistingMatchingCard(c210310305.spfilter1,tp,LOCATION_DECK,0,1,nil,e,tp) end
    Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,LOCATION_DECK)
end
function c210310305.spop1(e,tp,eg,ep,ev,re,r,rp)
    if Duel.GetLocationCount(tp,LOCATION_MZONE)<=0 then return end
    if not e:GetHandler():IsRelateToEffect(e) then return end
    Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_SPSUMMON)
    local g=Duel.SelectMatchingCard(tp,c210310305.spfilter1,tp,LOCATION_DECK,0,1,1,nil,e,tp)
    if g:GetCount()>0 then
        Duel.SpecialSummon(g,0,tp,tp,false,false,POS_FACEUP)
    end
end
--sp effect 2 e3
function c210310305.cfilter2(c,tp)
   return c:GetPreviousControler()==tp and c:IsPreviousLocation(LOCATION_MZONE) and bit.band(c:GetPreviousRaceOnField(),RACE_AQUA)==0 and c:IsArchetype(Archetype_0x18) and c:IsPreviousPosition(POS_FACEUP)
end
function c210310305.spcon2(e,tp,eg,ep,ev,re,r,rp)
    return eg:IsExists(c210310305.cfilter2,1,nil,tp)
end
function c210310305.spfilter2(c,e,tp)
   return  c:IsArchetype(Archetype_0x18) and c:IsRace(RACE_FAIRY) and c:IsCanBeSpecialSummoned(e,0,tp,false,false)
end
function c210310305.sptg2(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
        and not e:GetHandler():IsStatus(STATUS_CHAINING)
        and Duel.IsExistingMatchingCard(c210310305.spfilter2,tp,LOCATION_DECK,0,1,nil,e,tp) end
    Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,LOCATION_DECK)
end
function c210310305.spop2(e,tp,eg,ep,ev,re,r,rp)
    if Duel.GetLocationCount(tp,LOCATION_MZONE)<=0 then return end
    if not e:GetHandler():IsRelateToEffect(e) then return end
    Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_SPSUMMON)
    local g=Duel.SelectMatchingCard(tp,c210310305.spfilter2,tp,LOCATION_DECK,0,1,1,nil,e,tp)
    if g:GetCount()>0 then
        Duel.SpecialSummon(g,0,tp,tp,false,false,POS_FACEUP)
    end
end
--counter effect
function c210310305.target(e,tp,eg,ep,ev,re,r,rp,chk)
   if chk==0 then return Duel.
   Duel.SelectTarget(tp,Card.IsFaceup,tp,LOCATION_MZONE,LOCATION_MZONE,1,1,nil)
end
function c210310305.activate(e,tp,eg,ep,ev,re,r,rp)
    local tc=Duel.GetFirstTarget()
    if tc:IsFaceup() and tc:IsRelateToEffect(e) then
    tc:AddCounter(0x1019,2)
end

and 
Fog Dualities
Continuous Trap Card
Target 1 monster on the field, place 2 fog counters on it. When a Fairy-type "Cloudian" monster is removed from the field, except by its own effect: Special Summon 1 Aqua-type "Cloudian" monster from your deck or GY. When an Aqua-type "Cloudian" is removed from the field, except by its own effect: add 1 Fairy-type "Cloudian" monster from your deck to your hand. You can only activate each effect of "Fog Dualities" once per turn.

**Comment by Gh8stree** [comment]
what do I do now?

**Comment by AndreOliveiraMendes** [comment]
you need to send also cdb and images

**Comment by Gh8stree** [comment]
how do i edit this

**Comment by AndreOliveiraMendes** [comment]
make a pull request, choose either option as you repository, they first one choose patch 1 and segond choose master branch, they merge it.

**Comment by AndreOliveiraMendes** [comment]
closing that because of https://github.com/Gideon9212/Livecustom/pull/156

**Pull request closed without merging**
