### PR TITLE
Single card support for Relinquished

### PR DESCRIPTION
**Pull request by gecko-chan**
"Black Illusion Necromancy" field spell. Support for Relinquished and 'Eyes Restrict' fusion monsters.

### CODE REVIEW

**Comment by gecko-chan** [comment]
I'm not sure why those two "custom Watt" items appear in this pull request, since I thought they were already merged with my previous PR. But I can't get them to go away, so...

**Comment by AlphaKretin** [comment]
It's because those files have been changed in the main branch since your last PR was merged (for example, the database was merged with Livecustom.cdb). Don't make multiple pulls from the same branch, either delete your fork and make another one, or make another branch of this fork by, for example, going to Gideon9212/Livecustom and trying to create or edit a file. That will keep your new changes seperate from your old ones.

**Comment by AndreOliveiraMendes** [comment]
hum, try to delet you repository, then make a clean fork.
if you don't know, go on you fork (click fork)
click setings
last option is delet repository, click on it
back on https://github.com/Gideon9212/Livecustom and re-fork.

**Comment by AlphaKretin** [comment]
Oh, right, I'll go ahead and close this since you need to make a new one as Andre and I described anyway.

**Comment by gecko-chan** [comment]
Thanks

**Pull request closed without merging**
