### PR TITLE
Added new card: "Dimension Synchro"

### PR DESCRIPTION
**Pull request by EerieCode**
Dimension Synchro
Normal Spell
Pay 1500 LP, then reveal 1 Synchro Monster in your Extra Deck; banish Synchro Material Monsters from your hand, field, or that were sent from the field to the GY, whose total Levels equal double the revealed monster's Level, then Special Summon that monster from your Extra Deck (This is treated as a Synchro Summon.) You can only activate 1 "Dimension Synchro" per turn.

### CODE REVIEW

**Comment by Gideon9212** [comment]
So a instant fusion for synchros with no limit? As in I can build a lightsworn sycro mill deck, and summon quasar with this? 
Some checking of interactions are needed. Putting this on hold.

**Comment by EerieCode** [comment]
More like a mix between "Ancient Gear Factory" and "Dragon's Mirror", plus forcing you to use double the Level to make things a little more difficult. That being said, for the Quasar case specifically, consider this:
1. You still need to banish appropriate monsters, so 1 Synchro Tuner and 2+ Synchro monsters;
2. If you use monsters in the GY, those monsters must have been on the field before, so you'd still need to perform at least 3 Synchro Summons before being able to use this for Quasar.
Not sure how much it will help for balance, we'd need to test in in action, but in most scenarios, if you can set up the materials in the GY, you'd probably be able to set up the proper summon for Quasar just as easily.

**Comment by Gideon9212** [comment]
True but with decks that can summon at least 2 quasars, they can summon a 3rd with this much easyer and by using the same resources the last 2 used.
Though this interaction applys with anything really. Summon 2 stardust, summon 3rd with this, etc.
As such, need testing of how much this can setup a board thats in the middle of setting up with synchros to make sure we aren't adding something that can help decks that setup hard to break boards, to impossible to break boards.

**Comment by Gideon9212** [comment]
Can't find a interaction that's super broken. There is still some iffy interactions that I can see but I'll keep a eye on it.

**Pull request merged**
