### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MoonBurst**
on banish effect was too generic, fixed filter

### CODE REVIEW

**Comment by AndreOliveiraMendes** [comment]
you may revise line 66, is it really necessary? i don't see any need for it.

**Comment by MoonBurst** [comment]
Wait, what changed on line 66?

**Comment by AndreOliveiraMendes** [comment]
i'll explain, on line 66 you have (the most changes as formating and a forget and)
>function c515242591.spop2(e,tp,eg,ep,ev,re,r,rp)
        local hg=Duel.GetFieldGroup(1-tp,LOCATION_HAND,0)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATOEXTRA)
	local g=Duel.SelectMatchingCard(tp,c515242591.filter2,tp,LOCATION_GRAVE,0,1,2,nil)
	if g:GetCount()>0 then
		Duel.SendtoExtraP(g,nil,REASON_EFFECT)
	end
end

you define hg, but you don't use that anywhere on spop later, so was that definition really necessary?

**Comment by MoonBurst** [comment]
ahh, that might just be something from a script I pulled from to make it. I'm not sure if it actually does anything at that point.

**Comment by AndreOliveiraMendes** [comment]
im merging that, but you should make you chkc filter better (not checked all the chkc's), it was wrong
ps: you may consult ruling with necrovaley.

**Pull request merged**
