### PR TITLE
Nekroz Support

### PR DESCRIPTION
**Pull request by Terrieforming**

### CODE REVIEW

**Comment by AlphaKretin** [comment]
I can only just read Thunder Lord from the proxy... :V Looks fine, fits the Nekroz template and Mist Valley theming. Nekroz Meditation is also neat, Tributing (which I understand to be an action that synergises with some Nekroz cards?) to thin out the options for a search, while being a Magical Mallet for an archetype that's lost a lot of searchers to lists. Ilusion is also nifty for basically the same reason, and can dump spells for their effects in grave. All around a good set of cards. (Couldn't this PR just be called "Nekroz support", though? :V )

**Comment by AlphaKretin** [comment]
Oh... the art will be a problem though. You can't have the same image as an existing official card. I'm not familiar enough with Nekroz and related themes to recognise the Spell/Traps, so I don't know if they also offend, but Nekroz of Thunder Lord seems to just have Mist Valley Thunder Lord's art. You're going to have to change it.

**Comment by Terrieforming** [comment]
Made a few changes following your advice. They now sport a new look!

**Comment by AlphaKretin** [comment]
Just checked out the CDB, too, everything appears to be in order. Just gotta wait for Gideon to review the actual cards.

**Pull request merged**
