### PR TITLE
Added new custom cards

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by EerieCode** [comment]
Cards added by this request:
1. Supreme King Dragon Oddwurm
2. Supreme King Dragon Clearwurm
3. Supreme King Dragon Starwurm
4. Odd-Eyes Rebellion Dragon - Lightning Strike
5. Odd-Eyes Network Dragon

**Comment by Gideon9212** [comment]
On Odd-Eyes Network Dragon

> 2+ among "Performapal" monsters, "Odd-Eyes" monsters and "Magician" Pendulum monsters

This needs reworded better. Maybe
2+ "Performapal" monsters, "Odd-Eyes" monsters and/or "Magician" Pendulum monsters 
It depends on if all of the are meant to be pendulum or not.
Other this the above, the rest pass. Effects are fine and love the artwork.

**Comment by AlphaKretin** [comment]
c515220018, line 38 references a function that doesn't exist. Either it needs to change from sptg to sctg or the functions need to change vice versa

**Comment by AlphaKretin** [comment]
Clearwurm's effect to Synchro with the card in scale allows you to use 2 Tuners, fixing that seems a bit out of my league

**Comment by AlphaKretin** [comment]
OE Rebellion Lightning Strike doesn't actually summon itself after banishing the spell from graveyard

**Comment by AlphaKretin** [comment]
Lightning Strike crashes the game when you detach materials

**Comment by AlphaKretin** [comment]
Odd-Eyes Network Dragon's continuous attack boost doesn't seem to apply at all. That's everything - any effect or card I haven't mentioned works to my testing.

**Comment by AndreOliveiraMendes** [comment]
i think there a small issue with type check and pendulum zones, the game seems to forget the fact the card was a pendulum, but assume aparenty does the job, this

> function c515220018.scfilter2(c,mc,sc)
    local mg=Group.FromCards(c,mc)
    c:AssumeProperty(ASSUME_TYPE,c:GetOriginalType())
    return c:IsCanBeSynchroMaterial(sc) and sc:IsSynchroSummonable(nil,mg)
end

seems to solve the issue aparent, so i would say they need to revise the synchro part with szone.

**Comment by EerieCode** [comment]
@AlphaKretin I've uploaded a patch for the bugs you've reported: you can close your pull request, I've included your corrections and added André's suggestion and the updated SelectUnselect for Lightning Strike's alternate summon. Thank you very much!
Just one question, though: does that game still crash when detaching for Lightning Strike's effect? I checked its cost, and it's identical to Number C9's: I don't see anything in the script that could cause a crash.

**Comment by AlphaKretin** [comment]
No problem! I'll test Lightning Strike the next chance I get, though I should specify that it's not only the cost, the game crashed whenever it lost Xyz Materials, or at least also when leaving the field.

**Comment by AlphaKretin** [comment]
Ech, misremembered things early in the morning and can't edit comments on phone. I didn't actually test removing it from the field crash-wise except when it had a silly amount of materials, which can cause stability issues unrelated to the card, I only properly tested the cost indeed.

**Comment by Gideon9212** [comment]
Tests on script show issues for some, no issues for others. 
Currently unconfirmed on why. More script testing needed before merge.

**Comment by EerieCode** [comment]
After testing it, Lightning Strike seems to work as intended: as such, I'm approving this pull.

**Pull request merged**
